language: node_js
node_js: 
  - '16'
install:
  - npm install 
after_script:
  - cd ./build
  - git init
  - git config user.name "dezhizhang"
  - git config user.email "1541609448@qq.com"
  - git add -A
  - git commit -m 'Update documents'
  - git push --force "https://${GH_TOKEN}@${GH_REF}" "master:gh-pages"
branches:
  only:
    - master
